// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRIqK95sTqY7ToL21blNOg6e6WrHy-ClY',
    appId: '1:396479662232:web:6a430837e0f0b44f29e8ed',
    messagingSenderId: '396479662232',
    projectId: 'aquify-app',
    authDomain: 'aquify-app.firebaseapp.com',
    storageBucket: 'aquify-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhFPaJg4ezbpy1cAxD0ey2KSRt6tKtQrc',
    appId: '1:396479662232:android:c8c2bca246806ea029e8ed',
    messagingSenderId: '396479662232',
    projectId: 'aquify-app',
    storageBucket: 'aquify-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7KJeUXnyyctLZfB6dqTedEJJ6d0cUDFU',
    appId: '1:396479662232:ios:e33552c7963ab76b29e8ed',
    messagingSenderId: '396479662232',
    projectId: 'aquify-app',
    storageBucket: 'aquify-app.firebasestorage.app',
    iosBundleId: 'com.example.aquifyApp',
  );
}
